# Training
batch_size_per_gpu: 350
gradient_accumulation_steps: 1
n_updates: 10000
learning_rate: 0.0001
log_interval: 500

# these can vary but for convenience, here
embed_dim: 32
num_heads: 8
hidden_dim: 128
num_blocks: 2

# resume from checkpoint
checkpoint: null
