# wandb
use_wandb: true
wandb_project: tinyworlds

# dataset
dataset: PICODOOM
preload_ratio: 0.005

# shared model params
patch_size: 4
context_length: 4
frame_size: 64
latent_dim: 5 # for video tokenizer
num_bins: 4 # for video tokenizer
n_actions: 4

# performance
amp: true
tf32: true
compile: true

# distributed launch (torchrun)
distributed: 
  use_ddp: False
  use_fsdp: False
  reshard_after_forward: False
nproc_per_node: 1 # how many GPUs per node
standalone: true # if we're using one node, this eliminates extraneous processes

# stage configs
video_tokenizer_config: configs/video_tokenizer.yaml
latent_actions_config: configs/latent_actions.yaml
dynamics_config: configs/dynamics.yaml

# which stages to run
run_video_tokenizer: true
run_latent_actions: true
run_dynamics: true
