# Training
batch_size_per_gpu: 350
gradient_accumulation_steps: 1
n_updates: 40000
learning_rate: 0.001
log_interval: 2500

# these can vary but for convenience, here
embed_dim: 32
num_heads: 8
hidden_dim: 128
num_blocks: 4

# resume from checkpoint
checkpoint: